version: '3.8'

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: SQL-Server-Local
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SQL#1234
    ports:
      - "1433:1433"
    networks:
      - sql-network

networks:
  sql-network:
    driver: bridge

